# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: profiler/service/v1alpha1/profiler.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from profiler.domain.v1alpha1 import domain_pb2 as profiler_dot_domain_dot_v1alpha1_dot_domain__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(profiler/service/v1alpha1/profiler.proto\x12\x1eio.spoud.sdm.profiler.v1alpha1\x1a%profiler/domain/v1alpha1/domain.proto\"7\n\x0eProfileRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x11\n\tjson_data\x18\x02 \x01(\t\"w\n\x19ProfileDataStreamResponse\x12;\n\x04meta\x18\x01 \x01(\x0b\x32+.io.spoud.sdm.profiler.domain.v1alpha1.MetaH\x00\x12\x11\n\x07profile\x18\x02 \x01(\tH\x00\x42\n\n\x08response\"Z\n\x11InspectionRequest\x12\x14\n\x0csamples_json\x18\x01 \x01(\t\x12\x13\n\x0bschema_json\x18\x02 \x01(\t\x12\x1a\n\x12is_schema_inferred\x18\x03 \x01(\x08\"\xbc\x01\n\x1cInspectionDataStreamResponse\x12G\n\x06metric\x18\x01 \x01(\x0b\x32\x35.io.spoud.sdm.profiler.domain.v1alpha1.QualityMetricsH\x00\x12G\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x36.io.spoud.sdm.profiler.domain.v1alpha1.InspectionErrorH\x00\x42\n\n\x08response2\x95\x02\n\x08Profiler\x12\x82\x01\n\x11ProfileDataStream\x12..io.spoud.sdm.profiler.v1alpha1.ProfileRequest\x1a\x39.io.spoud.sdm.profiler.v1alpha1.ProfileDataStreamResponse(\x01\x30\x01\x12\x83\x01\n\x0eInspectQuality\x12\x31.io.spoud.sdm.profiler.v1alpha1.InspectionRequest\x1a<.io.spoud.sdm.profiler.v1alpha1.InspectionDataStreamResponse(\x01\x42*\n&io.spoud.sdm.profiler.service.v1alpha1P\x01\x62\x06proto3')



_PROFILEREQUEST = DESCRIPTOR.message_types_by_name['ProfileRequest']
_PROFILEDATASTREAMRESPONSE = DESCRIPTOR.message_types_by_name['ProfileDataStreamResponse']
_INSPECTIONREQUEST = DESCRIPTOR.message_types_by_name['InspectionRequest']
_INSPECTIONDATASTREAMRESPONSE = DESCRIPTOR.message_types_by_name['InspectionDataStreamResponse']
ProfileRequest = _reflection.GeneratedProtocolMessageType('ProfileRequest', (_message.Message,), {
  'DESCRIPTOR' : _PROFILEREQUEST,
  '__module__' : 'profiler.service.v1alpha1.profiler_pb2'
  # @@protoc_insertion_point(class_scope:io.spoud.sdm.profiler.v1alpha1.ProfileRequest)
  })
_sym_db.RegisterMessage(ProfileRequest)

ProfileDataStreamResponse = _reflection.GeneratedProtocolMessageType('ProfileDataStreamResponse', (_message.Message,), {
  'DESCRIPTOR' : _PROFILEDATASTREAMRESPONSE,
  '__module__' : 'profiler.service.v1alpha1.profiler_pb2'
  # @@protoc_insertion_point(class_scope:io.spoud.sdm.profiler.v1alpha1.ProfileDataStreamResponse)
  })
_sym_db.RegisterMessage(ProfileDataStreamResponse)

InspectionRequest = _reflection.GeneratedProtocolMessageType('InspectionRequest', (_message.Message,), {
  'DESCRIPTOR' : _INSPECTIONREQUEST,
  '__module__' : 'profiler.service.v1alpha1.profiler_pb2'
  # @@protoc_insertion_point(class_scope:io.spoud.sdm.profiler.v1alpha1.InspectionRequest)
  })
_sym_db.RegisterMessage(InspectionRequest)

InspectionDataStreamResponse = _reflection.GeneratedProtocolMessageType('InspectionDataStreamResponse', (_message.Message,), {
  'DESCRIPTOR' : _INSPECTIONDATASTREAMRESPONSE,
  '__module__' : 'profiler.service.v1alpha1.profiler_pb2'
  # @@protoc_insertion_point(class_scope:io.spoud.sdm.profiler.v1alpha1.InspectionDataStreamResponse)
  })
_sym_db.RegisterMessage(InspectionDataStreamResponse)

_PROFILER = DESCRIPTOR.services_by_name['Profiler']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n&io.spoud.sdm.profiler.service.v1alpha1P\001'
  _PROFILEREQUEST._serialized_start=115
  _PROFILEREQUEST._serialized_end=170
  _PROFILEDATASTREAMRESPONSE._serialized_start=172
  _PROFILEDATASTREAMRESPONSE._serialized_end=291
  _INSPECTIONREQUEST._serialized_start=293
  _INSPECTIONREQUEST._serialized_end=383
  _INSPECTIONDATASTREAMRESPONSE._serialized_start=386
  _INSPECTIONDATASTREAMRESPONSE._serialized_end=574
  _PROFILER._serialized_start=577
  _PROFILER._serialized_end=854
# @@protoc_insertion_point(module_scope)
