####
# This Dockerfile is used in order to build a container that runs the Quarkus application in JVM mode.
#
# Before building the container image run:
#
# ./mvnw package
#
# Then, build the image with:
#
# docker build -f Dockerfile.jvm -t spoud/agoora-profiler-service .
#
# Then run the container using:
#
# docker run -i --rm -p 8089:8089 -p 8280:8280 spoud/agoora-profiler-service
#
###
FROM cgr.dev/chainguard/jre:latest@sha256:553fa376d9ac5d23912a87bd6352acacbf96a08ba04202abbf16fa2bc02fdf14

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en'

# We make four distinct layers so if there are application changes the library layers can be re-used
COPY --chown=java:java target/quarkus-app/lib/ /deployments/lib/
COPY --chown=java:java target/quarkus-app/*.jar /deployments/
COPY --chown=java:java target/quarkus-app/app/ /deployments/app/
COPY --chown=java:java target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8089 8280 5005
USER java
ENTRYPOINT ["java", "-Dquarkus.http.host=0.0.0.0", "-Djava.util.logging.manager=org.jboss.logmanager.LogManager", "-jar", "/deployments/quarkus-run.jar"]
