####
# This Dockerfile is used in order to build a container that runs the Quarkus application in native (no JVM) mode.
#
# Before building the container image run:
#
# ./mvnw package -Pnative
#
# Then, build the image with:
#
# docker build -f Dockerfile.native -t spoud/agoora-profiler-service-native .
#
# Then run the container using:
#
# docker run -i --rm -p 8089:8089 -p 8281:8281 spoud/agoora-profiler-service-native
#
###
FROM quay.io/quarkus/quarkus-micro-image:2.0-2026-07-12
WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root target/*-runner /work/application

EXPOSE 8089 8281
USER 1001

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
