version: '3.7'
services:
  pgsql-agent:
    image: spoud/agoora-pgsql-agent
    build:
      context: agoora-pgsql-agent
    environment:
      - "AGOORA_PROFILER_ENDPOINT=agoora-profiler-service:8089"

  openapi-agent:
    image: spoud/agoora-openapi-agent
    build:
      context: agoora-openapi-agent
    environment:
      - "AGOORA_PROFILER_ENDPOINT=agoora-profiler-service:8089"

  mqtt-agent:
    image: spoud/agoora-mqtt-agent
    build:
      context: agoora-mqtt-agent
    environment:
      - "AGOORA_PROFILER_ENDPOINT=agoora-profiler-service:8089"
      - "AGOORA_ENDPOINT"
      - "AGOORA_INSECURE"
      - "AGOORA_TRANSPORT_PATH"
      - "AGOORA_AUTH_USER_NAME"
      - "AGOORA_AUTH_USER_TOKEN"
      - "AGOORA_MQTT_BROKER"
      - "AGOORA_MQTT_USERNAME"
      - "AGOORA_MQTT_PASSWORD"
      - "AGOORA_MQTT_PATHS"
      - "AGOORA_SCRAPPER_PERIOD=PT2M"
      - "AGOORA_SCRAPPER_MAX_WAIT=PT1M"
    extra_hosts:
      - "local.spoud.io:172.17.0.1"

  agoora-profiler-service:
    image: spoud/sdm-profiler-service
