version: '3.7'
services:
  pgsql-agent:
    image: spoud/sdm-pgsql-agent
    build:
      context: agoora-pgsql-agent
    environment:
      - "SDM_PROFILER_ENDPOINT=sdm-profiler-service:8089"
    networks:
      docker_sdm:

  sdm-profiler-service:
    image: spoud/sdm-profiler-service
    ports:
      - '8089:8089'
    networks:
      docker_sdm:

networks:
  docker_sdm:
    external: true
