version: '3.7'
services:
  pgsql-agent:
    image: spoud/agoora-pgsql-agent
    build:
      context: agoora-pgsql-agent
      dockerfile: Dockerfile.jar
    environment:
      - "AGOORA_PROFILER_ENDPOINT=agoora-profiler-service:8089"

  openapi-agent:
    image: spoud/agoora-openapi-agent
    build:
      context: agoora-openapi-agent
      dockerfile: Dockerfile.jar
    environment:
      - "AGOORA_PROFILER_ENDPOINT=agoora-profiler-service:8089"

  kafka-agent-native:
    image: spoud/agoora-kafka-agent:latest-native
    build:
      context: agoora-kafka-agent
      dockerfile: Dockerfile.native

  kafka-agent:
    image: spoud/agoora-kafka-agent
    build:
      context: agoora-kafka-agent
      dockerfile: Dockerfile.jvm
    environment:
      - "AGOORA_PROFILER_ENDPOINT=agoora-profiler-service:8089"
      - "AGOORA_ENDPOINT"
      - "AGOORA_INSECURE"
      - "AGOORA_TRANSPORT_PATH"
      - "AGOORA_AUTH_USER_NAME"
      - "AGOORA_AUTH_USER_TOKEN"
      - "AGOORA_KAFKA_BOOTSTRAP_SERVERS"
      - "AGOORA_SCRAPPER_PERIOD=PT2M"
    extra_hosts:
      - "local.spoud.io:172.17.0.1"
      - "kafka:172.17.0.1"

  mqtt-agent:
    image: spoud/agoora-mqtt-agent
    build:
      context: agoora-mqtt-agent
      dockerfile: Dockerfile.jar
    environment:
      - "AGOORA_PROFILER_ENDPOINT=agoora-profiler-service:8089"
      - "AGOORA_ENDPOINT"
      - "AGOORA_INSECURE"
      - "AGOORA_TRANSPORT_PATH"
      - "AGOORA_AUTH_USER_NAME"
      - "AGOORA_AUTH_USER_TOKEN"
      - "AGOORA_MQTT_BROKER"
      - "AGOORA_MQTT_USERNAME"
      - "AGOORA_MQTT_PASSWORD"
      - "AGOORA_MQTT_PATHS"
      - "AGOORA_SCRAPPER_PERIOD=PT2M"
      - "AGOORA_SCRAPPER_MAX_WAIT=PT1M"
    extra_hosts:
      - "local.spoud.io:172.17.0.1"

  profiler-service:
    image: spoud/agoora-profiler-service
    build:
      context: agoora-profiler-service/
      dockerfile: Dockerfile.jvm
    ports:
      - '8089:8089'
