# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: profiler/domain/v1alpha1/domain.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='profiler/domain/v1alpha1/domain.proto',
  package='io.spoud.sdm.profiler.domain.v1alpha1',
  syntax='proto3',
  serialized_options=b'\n%io.spoud.sdm.profiler.domain.v1alpha1P\001',
  serialized_pb=b'\n%profiler/domain/v1alpha1/domain.proto\x12%io.spoud.sdm.profiler.domain.v1alpha1\"\xd1\x01\n\rProfilerError\x12\x0f\n\x07message\x18\x01 \x01(\t\x12G\n\x04type\x18\x02 \x01(\x0e\x32\x39.io.spoud.sdm.profiler.domain.v1alpha1.ProfilerError.Type\"f\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x14\n\x10UNKNOWN_ENCODING\x10\x01\x12\x0b\n\x07NO_DATA\x10\x02\x12\x17\n\x0fPROFILE_TOO_BIG\x10\x03\x1a\x02\x08\x01\x12\x15\n\x11PROFILE_EXCEPTION\x10\x04\"\xd4\x01\n\x04Meta\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0e\n\x06schema\x18\x03 \x01(\t\x12\x43\n\x05\x65rror\x18\x04 \x01(\x0b\x32\x34.io.spoud.sdm.profiler.domain.v1alpha1.ProfilerError\x12\x17\n\x0fservice_version\x18\x05 \x01(\t\x12\x15\n\rtotal_records\x18\x06 \x01(\x05\x12\x18\n\x10schema_byte_size\x18\x07 \x01(\x05\x12\x19\n\x11profile_byte_size\x18\x08 \x01(\x05\"\xc2\x01\n\x0eQualityMetrics\x12\x1f\n\x17\x61ttribute_quality_index\x18\x01 \x01(\x02\x12\x1b\n\x13\x61ttribute_integrity\x18\x02 \x01(\x02\x12\x1f\n\x17\x61ttribute_specification\x18\x03 \x01(\x02\x12Q\n\x11\x61ttribute_details\x18\x04 \x03(\x0b\x32\x36.io.spoud.sdm.profiler.domain.v1alpha1.AttributeDetail\"`\n\x0f\x41ttributeDetail\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tintegrity\x18\x02 \x01(\x02\x12\x15\n\rspecification\x18\x03 \x01(\x02\x12\x15\n\rquality_index\x18\x04 \x01(\x02\"\xa5\x01\n\x0fInspectionError\x12\x0f\n\x07message\x18\x01 \x01(\t\x12I\n\x04type\x18\x02 \x01(\x0e\x32;.io.spoud.sdm.profiler.domain.v1alpha1.InspectionError.Type\"6\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x14\n\x10UNKNOWN_ENCODING\x10\x01\x12\x0b\n\x07NO_DATA\x10\x02\x42)\n%io.spoud.sdm.profiler.domain.v1alpha1P\x01\x62\x06proto3'
)



_PROFILERERROR_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='io.spoud.sdm.profiler.domain.v1alpha1.ProfilerError.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_ENCODING', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NO_DATA', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROFILE_TOO_BIG', index=3, number=3,
      serialized_options=b'\010\001',
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROFILE_EXCEPTION', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=188,
  serialized_end=290,
)
_sym_db.RegisterEnumDescriptor(_PROFILERERROR_TYPE)

_INSPECTIONERROR_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='io.spoud.sdm.profiler.domain.v1alpha1.InspectionError.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_ENCODING', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NO_DATA', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=188,
  serialized_end=242,
)
_sym_db.RegisterEnumDescriptor(_INSPECTIONERROR_TYPE)


_PROFILERERROR = _descriptor.Descriptor(
  name='ProfilerError',
  full_name='io.spoud.sdm.profiler.domain.v1alpha1.ProfilerError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='io.spoud.sdm.profiler.domain.v1alpha1.ProfilerError.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='io.spoud.sdm.profiler.domain.v1alpha1.ProfilerError.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PROFILERERROR_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=290,
)


_META = _descriptor.Descriptor(
  name='Meta',
  full_name='io.spoud.sdm.profiler.domain.v1alpha1.Meta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='io.spoud.sdm.profiler.domain.v1alpha1.Meta.request_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='schema', full_name='io.spoud.sdm.profiler.domain.v1alpha1.Meta.schema', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='io.spoud.sdm.profiler.domain.v1alpha1.Meta.error', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service_version', full_name='io.spoud.sdm.profiler.domain.v1alpha1.Meta.service_version', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_records', full_name='io.spoud.sdm.profiler.domain.v1alpha1.Meta.total_records', index=4,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='schema_byte_size', full_name='io.spoud.sdm.profiler.domain.v1alpha1.Meta.schema_byte_size', index=5,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='profile_byte_size', full_name='io.spoud.sdm.profiler.domain.v1alpha1.Meta.profile_byte_size', index=6,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=293,
  serialized_end=505,
)


_QUALITYMETRICS = _descriptor.Descriptor(
  name='QualityMetrics',
  full_name='io.spoud.sdm.profiler.domain.v1alpha1.QualityMetrics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='attribute_quality_index', full_name='io.spoud.sdm.profiler.domain.v1alpha1.QualityMetrics.attribute_quality_index', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attribute_integrity', full_name='io.spoud.sdm.profiler.domain.v1alpha1.QualityMetrics.attribute_integrity', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attribute_specification', full_name='io.spoud.sdm.profiler.domain.v1alpha1.QualityMetrics.attribute_specification', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attribute_details', full_name='io.spoud.sdm.profiler.domain.v1alpha1.QualityMetrics.attribute_details', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=508,
  serialized_end=702,
)


_ATTRIBUTEDETAIL = _descriptor.Descriptor(
  name='AttributeDetail',
  full_name='io.spoud.sdm.profiler.domain.v1alpha1.AttributeDetail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='io.spoud.sdm.profiler.domain.v1alpha1.AttributeDetail.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='integrity', full_name='io.spoud.sdm.profiler.domain.v1alpha1.AttributeDetail.integrity', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='specification', full_name='io.spoud.sdm.profiler.domain.v1alpha1.AttributeDetail.specification', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quality_index', full_name='io.spoud.sdm.profiler.domain.v1alpha1.AttributeDetail.quality_index', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=704,
  serialized_end=800,
)


_INSPECTIONERROR = _descriptor.Descriptor(
  name='InspectionError',
  full_name='io.spoud.sdm.profiler.domain.v1alpha1.InspectionError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='io.spoud.sdm.profiler.domain.v1alpha1.InspectionError.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='io.spoud.sdm.profiler.domain.v1alpha1.InspectionError.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _INSPECTIONERROR_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=803,
  serialized_end=968,
)

_PROFILERERROR.fields_by_name['type'].enum_type = _PROFILERERROR_TYPE
_PROFILERERROR_TYPE.containing_type = _PROFILERERROR
_META.fields_by_name['error'].message_type = _PROFILERERROR
_QUALITYMETRICS.fields_by_name['attribute_details'].message_type = _ATTRIBUTEDETAIL
_INSPECTIONERROR.fields_by_name['type'].enum_type = _INSPECTIONERROR_TYPE
_INSPECTIONERROR_TYPE.containing_type = _INSPECTIONERROR
DESCRIPTOR.message_types_by_name['ProfilerError'] = _PROFILERERROR
DESCRIPTOR.message_types_by_name['Meta'] = _META
DESCRIPTOR.message_types_by_name['QualityMetrics'] = _QUALITYMETRICS
DESCRIPTOR.message_types_by_name['AttributeDetail'] = _ATTRIBUTEDETAIL
DESCRIPTOR.message_types_by_name['InspectionError'] = _INSPECTIONERROR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProfilerError = _reflection.GeneratedProtocolMessageType('ProfilerError', (_message.Message,), {
  'DESCRIPTOR' : _PROFILERERROR,
  '__module__' : 'profiler.domain.v1alpha1.domain_pb2'
  # @@protoc_insertion_point(class_scope:io.spoud.sdm.profiler.domain.v1alpha1.ProfilerError)
  })
_sym_db.RegisterMessage(ProfilerError)

Meta = _reflection.GeneratedProtocolMessageType('Meta', (_message.Message,), {
  'DESCRIPTOR' : _META,
  '__module__' : 'profiler.domain.v1alpha1.domain_pb2'
  # @@protoc_insertion_point(class_scope:io.spoud.sdm.profiler.domain.v1alpha1.Meta)
  })
_sym_db.RegisterMessage(Meta)

QualityMetrics = _reflection.GeneratedProtocolMessageType('QualityMetrics', (_message.Message,), {
  'DESCRIPTOR' : _QUALITYMETRICS,
  '__module__' : 'profiler.domain.v1alpha1.domain_pb2'
  # @@protoc_insertion_point(class_scope:io.spoud.sdm.profiler.domain.v1alpha1.QualityMetrics)
  })
_sym_db.RegisterMessage(QualityMetrics)

AttributeDetail = _reflection.GeneratedProtocolMessageType('AttributeDetail', (_message.Message,), {
  'DESCRIPTOR' : _ATTRIBUTEDETAIL,
  '__module__' : 'profiler.domain.v1alpha1.domain_pb2'
  # @@protoc_insertion_point(class_scope:io.spoud.sdm.profiler.domain.v1alpha1.AttributeDetail)
  })
_sym_db.RegisterMessage(AttributeDetail)

InspectionError = _reflection.GeneratedProtocolMessageType('InspectionError', (_message.Message,), {
  'DESCRIPTOR' : _INSPECTIONERROR,
  '__module__' : 'profiler.domain.v1alpha1.domain_pb2'
  # @@protoc_insertion_point(class_scope:io.spoud.sdm.profiler.domain.v1alpha1.InspectionError)
  })
_sym_db.RegisterMessage(InspectionError)


DESCRIPTOR._options = None
_PROFILERERROR_TYPE.values_by_name["PROFILE_TOO_BIG"]._options = None
# @@protoc_insertion_point(module_scope)
