# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: profiler/domain/v1alpha1/domain.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%profiler/domain/v1alpha1/domain.proto\x12%io.spoud.sdm.profiler.domain.v1alpha1\"\xd1\x01\n\rProfilerError\x12\x0f\n\x07message\x18\x01 \x01(\t\x12G\n\x04type\x18\x02 \x01(\x0e\x32\x39.io.spoud.sdm.profiler.domain.v1alpha1.ProfilerError.Type\"f\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x14\n\x10UNKNOWN_ENCODING\x10\x01\x12\x0b\n\x07NO_DATA\x10\x02\x12\x17\n\x0fPROFILE_TOO_BIG\x10\x03\x1a\x02\x08\x01\x12\x15\n\x11PROFILE_EXCEPTION\x10\x04\"\xd4\x01\n\x04Meta\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0e\n\x06schema\x18\x03 \x01(\t\x12\x43\n\x05\x65rror\x18\x04 \x01(\x0b\x32\x34.io.spoud.sdm.profiler.domain.v1alpha1.ProfilerError\x12\x17\n\x0fservice_version\x18\x05 \x01(\t\x12\x15\n\rtotal_records\x18\x06 \x01(\x05\x12\x18\n\x10schema_byte_size\x18\x07 \x01(\x05\x12\x19\n\x11profile_byte_size\x18\x08 \x01(\x05\"\xc2\x01\n\x0eQualityMetrics\x12\x1f\n\x17\x61ttribute_quality_index\x18\x01 \x01(\x02\x12\x1b\n\x13\x61ttribute_integrity\x18\x02 \x01(\x02\x12\x1f\n\x17\x61ttribute_specification\x18\x03 \x01(\x02\x12Q\n\x11\x61ttribute_details\x18\x04 \x03(\x0b\x32\x36.io.spoud.sdm.profiler.domain.v1alpha1.AttributeDetail\"`\n\x0f\x41ttributeDetail\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tintegrity\x18\x02 \x01(\x02\x12\x15\n\rspecification\x18\x03 \x01(\x02\x12\x15\n\rquality_index\x18\x04 \x01(\x02\"\xa5\x01\n\x0fInspectionError\x12\x0f\n\x07message\x18\x01 \x01(\t\x12I\n\x04type\x18\x02 \x01(\x0e\x32;.io.spoud.sdm.profiler.domain.v1alpha1.InspectionError.Type\"6\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x14\n\x10UNKNOWN_ENCODING\x10\x01\x12\x0b\n\x07NO_DATA\x10\x02\x42)\n%io.spoud.sdm.profiler.domain.v1alpha1P\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'profiler.domain.v1alpha1.domain_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n%io.spoud.sdm.profiler.domain.v1alpha1P\001'
  _PROFILERERROR_TYPE.values_by_name["PROFILE_TOO_BIG"]._options = None
  _PROFILERERROR_TYPE.values_by_name["PROFILE_TOO_BIG"]._serialized_options = b'\010\001'
  _PROFILERERROR._serialized_start=81
  _PROFILERERROR._serialized_end=290
  _PROFILERERROR_TYPE._serialized_start=188
  _PROFILERERROR_TYPE._serialized_end=290
  _META._serialized_start=293
  _META._serialized_end=505
  _QUALITYMETRICS._serialized_start=508
  _QUALITYMETRICS._serialized_end=702
  _ATTRIBUTEDETAIL._serialized_start=704
  _ATTRIBUTEDETAIL._serialized_end=800
  _INSPECTIONERROR._serialized_start=803
  _INSPECTIONERROR._serialized_end=968
  _INSPECTIONERROR_TYPE._serialized_start=188
  _INSPECTIONERROR_TYPE._serialized_end=242
# @@protoc_insertion_point(module_scope)
