package io.spoud.agoora.agents.kafka.metrics;

public enum MetricsType {
  DATA_PORT_MESSAGES_COUNT,
  DATA_PORT_BYTES,
  DATA_SUBSCRIPTION_STATE_MESSAGES_COUNT,
  DATA_SUBSCRIPTION_STATE_BYTES,
  DATA_SUBSCRIPTION_STATE_MESSAGES_LAG_COUNT
}
