sdm-endpoint: local.spoud.io
sdm-insecure: false
sdm-cluster: default
sdm-transport-path: /default/mqtt

sdm:
  # The scrapper is not on 100% of the time. It start listening every {period} for a maximum of {max-samples} messages and {max-wait}
  scrapper:
    max-samples: 100
    period: 1H
    max-wait: 30M
    profiling:
      enabled: true
    hooks:
      enabled: true
  mqtt:
    broker: tcp://192.168.1.11:1883
    username:
    password:
    client-id: mqtt-agent
    paths: zigbee2mqtt_bas/bridge/,zigbee2mqtt_bas/bridge/
  transport:
    sdm-path: ${sdm-transport-path}
  auth:
    server-url: https://${sdm-endpoint}/auth/
    cluster: ${sdm-cluster}
    realm: spoud
    user:
      name: to-be-defined
      token: to-be-defined
  logistics:
    endpoint: ${sdm-endpoint}
    cluster: ${sdm-cluster}
    insecure: ${sdm-insecure}
  hooks:
    endpoint: ${sdm-endpoint}
    cluster: ${sdm-cluster}
    insecure: ${sdm-insecure}
  schema:
    endpoint: ${sdm-endpoint}
    cluster: ${sdm-cluster}
    insecure: ${sdm-insecure}
  looker:
    endpoint: ${sdm-endpoint}
    cluster: ${sdm-cluster}
    insecure: ${sdm-insecure}
  blob:
    endpoint: ${sdm-endpoint}
    cluster: ${sdm-cluster}
    insecure: ${sdm-insecure}
  profiler:
    endpoint: localhost:8089
    insecure: true

quarkus:
  arc:
    # Needed for the grpc interceptors
    remove-unused-beans: fwk
  http:
    port: 8280
  log:
    category:
      "io.spoud.sdm":
        level: INFO
  ssl:
    native: true
  native:
    additional-build-args:
      - --allow-incomplete-classpath
      - --report-unsupported-elements-at-runtime
      - -H:IncludeResourceBundles=org.eclipse.paho.client.mqttv3.internal.nls.logcat,org.eclipse.paho.client.mqttv3.internal.nls.messages

"%dev":
  sdm-endpoint: local.spoud.io
  sdm-insecure: true
  sdm-cluster: default
  sdm-transport-path: /default/mqtt/mqtt
  sdm:
    scrapper:
      max-samples: 10
      period: 10M
      max-wait: 5M
    auth:
      server-url: http://${sdm-endpoint}/auth/
      user:
        name: sdm_t_672923a1-9fd9-4743-92fd-3935fc56d986
        token: cmBcp9aOfUtKdH05bSK03kEwFFO89LO6


  quarkus:
    log:
      category:
        "io.spoud.sdm":
          level: DEBUG
