agoora-endpoint: local.spoud.io
agoora-insecure: false
agoora-cluster: default
agoora-transport-path: /default/mqtt

agoora:
  # The scrapper is not on 100% of the time. It start listening every {period} for a maximum of {max-samples} messages and {max-wait}
  scrapper:
    max-samples: 100
    period: 1H
    max-wait: 30M
    profiling:
      enabled: true
    hooks:
      enabled: true
    wait-time-before-counting-retained: PT15S
  mqtt:
    broker: tcp://192.168.1.11:1883
    username:
    password:
    client-id: mqtt-agent
    paths: zigbee2mqtt_bas/bridge/,zigbee2mqtt_bas/bridge/
  transport:
    agoora-path: ${agoora-transport-path}
  auth:
    server-url: https://${agoora-endpoint}/auth/
    realm: spoud
    user:
      name: to-be-defined
      token: to-be-defined
  logistics:
    endpoint: ${agoora-endpoint}
    insecure: ${agoora-insecure}
  hooks:
    endpoint: ${agoora-endpoint}
    insecure: ${agoora-insecure}
  schema:
    endpoint: ${agoora-endpoint}
    insecure: ${agoora-insecure}
  looker:
    endpoint: ${agoora-endpoint}
    insecure: ${agoora-insecure}
  blob:
    endpoint: ${agoora-endpoint}
    insecure: ${agoora-insecure}
  profiler:
    endpoint: localhost:8089
    insecure: true

quarkus:
  arc:
    # Needed for the grpc interceptors
    remove-unused-beans: fwk
  http:
    port: 8280
  log:
    category:
      "io.spoud.agoora":
        level: INFO
  ssl:
    native: true
  native:
    container-build: true
    additional-build-args:
      - --allow-incomplete-classpath
      - --report-unsupported-elements-at-runtime
      - -H:IncludeResourceBundles=org.eclipse.paho.client.mqttv3.internal.nls.logcat,org.eclipse.paho.client.mqttv3.internal.nls.messages

"%dev":
  agoora-endpoint: local.spoud.io
  agoora-insecure: true
  agoora-cluster: default
  agoora-transport-path: /default/mqtt/mqtt
  agoora:
    scrapper:
      max-samples: 10
      period: 10M
      max-wait: 5M
    auth:
      server-url: http://${agoora-endpoint}/auth/
      user:
        name: agoora_t_672923a1-9fd9-4743-92fd-3935fc56d986
        token: cmBcp9aOfUtKdH05bSK03kEwFFO89LO6


  quarkus:
    log:
      category:
        "io.spoud.agoora":
          level: DEBUG
