name: Java build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Xmx4g

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: DeLaGuardo/setup-graalvm@4.0
        with:
          graalvm: '21.0.0.2'
          java: 'java11'
          arch: 'amd64'
      - name: Maven version
        run: mvn -v
      - name: Build with Maven
        run: mvn --batch-mode clean package

